"""add blacklist table

Revision ID: 737085becc95
Revises: a2d311a9d29c
Create Date: 2020-06-28 23:48:28.001969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '737085becc95'
down_revision = 'a2d311a9d29c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
